export interface Technique {
  id: string;
  name: string;
}

export interface Tactic {
  name: string;
  techniques: Technique[];
}

// Abbreviated Enterprise Matrix Data - Full version has 4000+ techniques
export const mitreEnterpriseMatrixData: Tactic[] = [
  {
    name: "Initial Access",
    techniques: [
      { id: "T1189", name: "Drive-by Compromise" },
      { id: "T1190", name: "Exploit Public-Facing Application" },
      { id: "T1133", name: "External Remote Services" },
      { id: "T1200", name: "Hardware Additions" },
      { id: "T1566", name: "Phishing" },
      { id: "T1566.001", name: "Spearphishing Attachment" },
      { id: "T1566.002", name: "Spearphishing Link" },
      { id: "T1566.003", name: "Spearphishing via Service" },
      { id: "T1091", name: "Replication Through Removable Media" },
      { id: "T1195", name: "Supply Chain Compromise" },
      { id: "T1199", name: "Trusted Relationship" },
      { id: "T1078", name: "Valid Accounts" },
    ],
  },
  {
    name: "Execution",
    techniques: [
      { id: "T1059", name: "Command and Scripting Interpreter" },
      { id: "T1059.001", name: "PowerShell" },
      { id: "T1059.003", name: "Windows Command Shell" },
      { id: "T1059.004", name: "Unix Shell" },
      { id: "T1059.005", name: "Visual Basic" },
      { id: "T1059.006", name: "Python" },
      { id: "T1059.007", name: "JavaScript" },
      { id: "T1203", name: "Exploitation for Client Execution" },
      { id: "T1106", name: "Native API" },
      { id: "T1053", name: "Scheduled Task/Job" },
      { id: "T1204", name: "User Execution" },
      { id: "T1047", name: "Windows Management Instrumentation" },
    ],
  },
  {
    name: "Persistence",
    techniques: [
      { id: "T1098", name: "Account Manipulation" },
      { id: "T1547", name: "Boot or Logon Autostart Execution" },
      { id: "T1547.001", name: "Registry Run Keys / Startup Folder" },
      { id: "T1136", name: "Create Account" },
      { id: "T1543", name: "Create or Modify System Process" },
      { id: "T1546", name: "Event Triggered Execution" },
      { id: "T1133", name: "External Remote Services" },
      { id: "T1574", name: "Hijack Execution Flow" },
      { id: "T1053", name: "Scheduled Task/Job" },
      { id: "T1505", name: "Server Software Component" },
      { id: "T1078", name: "Valid Accounts" },
    ],
  },
  {
    name: "Privilege Escalation",
    techniques: [
      { id: "T1548", name: "Abuse Elevation Control Mechanism" },
      { id: "T1134", name: "Access Token Manipulation" },
      { id: "T1547", name: "Boot or Logon Autostart Execution" },
      { id: "T1068", name: "Exploitation for Privilege Escalation" },
      { id: "T1574", name: "Hijack Execution Flow" },
      { id: "T1055", name: "Process Injection" },
      { id: "T1053", name: "Scheduled Task/Job" },
      { id: "T1078", name: "Valid Accounts" },
    ],
  },
  {
    name: "Defense Evasion",
    techniques: [
      { id: "T1140", name: "Deobfuscate/Decode Files or Information" },
      { id: "T1070", name: "Indicator Removal" },
      { id: "T1070.001", name: "Clear Windows Event Logs" },
      { id: "T1070.004", name: "File Deletion" },
      { id: "T1036", name: "Masquerading" },
      { id: "T1027", name: "Obfuscated Files or Information" },
      { id: "T1055", name: "Process Injection" },
      { id: "T1014", name: "Rootkit" },
      { id: "T1218", name: "System Binary Proxy Execution" },
      { id: "T1078", name: "Valid Accounts" },
    ],
  },
  {
    name: "Credential Access",
    techniques: [
      { id: "T1110", name: "Brute Force" },
      { id: "T1555", name: "Credentials from Password Stores" },
      { id: "T1212", name: "Exploitation for Credential Access" },
      { id: "T1187", name: "Forced Authentication" },
      { id: "T1056", name: "Input Capture" },
      { id: "T1556", name: "Modify Authentication Process" },
      { id: "T1003", name: "OS Credential Dumping" },
      { id: "T1003.001", name: "LSASS Memory" },
      { id: "T1528", name: "Steal Application Access Token" },
      { id: "T1539", name: "Steal Web Session Cookie" },
    ],
  },
  {
    name: "Discovery",
    techniques: [
      { id: "T1087", name: "Account Discovery" },
      { id: "T1083", name: "File and Directory Discovery" },
      { id: "T1046", name: "Network Service Discovery" },
      { id: "T1135", name: "Network Share Discovery" },
      { id: "T1057", name: "Process Discovery" },
      { id: "T1018", name: "Remote System Discovery" },
      { id: "T1082", name: "System Information Discovery" },
      { id: "T1016", name: "System Network Configuration Discovery" },
      { id: "T1049", name: "System Network Connections Discovery" },
      { id: "T1033", name: "System Owner/User Discovery" },
    ],
  },
  {
    name: "Lateral Movement",
    techniques: [
      { id: "T1210", name: "Exploitation of Remote Services" },
      { id: "T1534", name: "Internal Spearphishing" },
      { id: "T1570", name: "Lateral Tool Transfer" },
      { id: "T1021", name: "Remote Services" },
      { id: "T1021.001", name: "Remote Desktop Protocol" },
      { id: "T1021.002", name: "SMB/Windows Admin Shares" },
      { id: "T1021.004", name: "SSH" },
      { id: "T1072", name: "Software Deployment Tools" },
      { id: "T1080", name: "Taint Shared Content" },
      { id: "T1550", name: "Use Alternate Authentication Material" },
    ],
  },
  {
    name: "Collection",
    techniques: [
      { id: "T1560", name: "Archive Collected Data" },
      { id: "T1123", name: "Audio Capture" },
      { id: "T1119", name: "Automated Collection" },
      { id: "T1115", name: "Clipboard Data" },
      { id: "T1530", name: "Data from Cloud Storage" },
      { id: "T1213", name: "Data from Information Repositories" },
      { id: "T1005", name: "Data from Local System" },
      { id: "T1039", name: "Data from Network Shared Drive" },
      { id: "T1114", name: "Email Collection" },
      { id: "T1113", name: "Screen Capture" },
    ],
  },
  {
    name: "Command and Control",
    techniques: [
      { id: "T1071", name: "Application Layer Protocol" },
      { id: "T1071.001", name: "Web Protocols" },
      { id: "T1071.004", name: "DNS" },
      { id: "T1132", name: "Data Encoding" },
      { id: "T1001", name: "Data Obfuscation" },
      { id: "T1573", name: "Encrypted Channel" },
      { id: "T1008", name: "Fallback Channels" },
      { id: "T1105", name: "Ingress Tool Transfer" },
      { id: "T1095", name: "Non-Application Layer Protocol" },
      { id: "T1572", name: "Protocol Tunneling" },
      { id: "T1090", name: "Proxy" },
      { id: "T1219", name: "Remote Access Software" },
    ],
  },
  {
    name: "Exfiltration",
    techniques: [
      { id: "T1020", name: "Automated Exfiltration" },
      { id: "T1030", name: "Data Transfer Size Limits" },
      { id: "T1048", name: "Exfiltration Over Alternative Protocol" },
      { id: "T1041", name: "Exfiltration Over C2 Channel" },
      { id: "T1011", name: "Exfiltration Over Other Network Medium" },
      { id: "T1052", name: "Exfiltration Over Physical Medium" },
      { id: "T1567", name: "Exfiltration Over Web Service" },
      { id: "T1029", name: "Scheduled Transfer" },
      { id: "T1537", name: "Transfer Data to Cloud Account" },
    ],
  },
  {
    name: "Impact",
    techniques: [
      { id: "T1531", name: "Account Access Removal" },
      { id: "T1485", name: "Data Destruction" },
      { id: "T1486", name: "Data Encrypted for Impact" },
      { id: "T1565", name: "Data Manipulation" },
      { id: "T1491", name: "Defacement" },
      { id: "T1561", name: "Disk Wipe" },
      { id: "T1499", name: "Endpoint Denial of Service" },
      { id: "T1495", name: "Firmware Corruption" },
      { id: "T1490", name: "Inhibit System Recovery" },
      { id: "T1498", name: "Network Denial of Service" },
      { id: "T1496", name: "Resource Hijacking" },
      { id: "T1489", name: "Service Stop" },
      { id: "T1529", name: "System Shutdown/Reboot" },
    ],
  },
];


